# 1. PUERTO (Din\u00E1mico para Render/Local)
server.port=${PORT:8082}

# 2. CONFIGURACI\u00D3N DE BASE DE DATOS (IMPORTANTE)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/madridlink_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:madridlink2026}

# 3. PERSISTENCIA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. CARGA INICIAL
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true