# 1. PUERTO
server.port=8082

# 2. CONEXIÓN PERMANENTE (Guarda los datos en una carpeta 'data')
spring.datasource.url=jdbc:h2:file:./data/madridlink_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 3. PERSISTENCIA (Mantiene los datos al apagar el servidor)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# 4. CARGA INICIAL (Solo si quieres que el import.sql se ejecute siempre)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# 5. CONSOLA H2 (Accede en localhost:8082/h2-console)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true