# 1. PUERTO
server.port=${PORT:10000}

# 2. CONFIGURACI\u00D3N DE BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/madridlink_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:madridlink2026}
spring.datasource.driver-class-name=${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}


# 3. PERSISTENCIA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. CARGA INICIAL (Activada para llenar las tablas vac\u00EDas)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luisa.rincond95@gmail.com
spring.mail.password=aort vdmi quhg fijl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true